import { Restaurant, MenuItem, LoyaltyReward, Review, UserLoyalty } from "./types";

export const initialRestaurants: Restaurant[] = [
  {
    id: 1,
    name: "The Saffron Taj",
    cuisine: "North Indian • Mughlai • Tandoor • Desserts",
    tagline: "Traditional Royal Recipes from Imperial Kitchens",
    rating: 4.8,
    reviewCount: 24,
    deliveryTime: "30-40 mins",
    costForTwo: "₹1,200 for two",
    address: "Block C, Connaught Place, New Delhi",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 2,
    name: "Dakshin Palace",
    cuisine: "South Indian • Chettinad • Coastal Gold • Desserts",
    tagline: "The Magic of Curry Leaves, Mustard Seeds & Coconut",
    rating: 4.7,
    reviewCount: 18,
    deliveryTime: "25-35 mins",
    costForTwo: "₹800 for two",
    address: "Indiranagar, 100 Feet Road, Bengaluru",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: 3,
    name: "Clay Oven Punjabi",
    cuisine: "Punjabi Dhaba • Clay Oven • Spicy • Desserts",
    tagline: "Rich, Robust, and Full of Love from Amritsar",
    rating: 4.6,
    reviewCount: 15,
    deliveryTime: "35-45 mins",
    costForTwo: "₹700 for two",
    address: "Juhu Tara Road, Juhu, Mumbai",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800"
  }
];

export const initialMenuItems: MenuItem[] = [
  // The Saffron Taj (restaurantId = 1)
  {
    id: 101,
    restaurantId: 1,
    name: "Tandoori Saffron Paneer Tikka",
    description: "Paneer cubes marinated in rich spiced yogurt, saffron, and tandoori spices, char-roasted in direct flames.",
    price: 320.0,
    category: "Starters",
    isVeg: true,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: true,
    rating: 4.7,
    reviewCount: 11,
    imageUrl: "/images/dishes/101.png"
  },
  {
    id: 102,
    restaurantId: 1,
    name: "Murg Malai Kebab",
    description: "Boneless chicken chunks marinated in heavy cardamom cream, grated cheese, and soft white pepper.",
    price: 380.0,
    category: "Starters",
    isVeg: false,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.5,
    reviewCount: 4,
    imageUrl: "/images/dishes/102.png"
  },
  {
    id: 103,
    restaurantId: 1,
    name: "Grand Royal Butter Chicken",
    description: "Tender coal-smoked chicken pieces simmered in rich buttery tomato sauce, cashew paste, and raw honey glaze.",
    price: 450.0,
    category: "Mains",
    isVeg: false,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: true,
    rating: 4.9,
    reviewCount: 32,
    imageUrl: "/images/dishes/103.png"
  },
  {
    id: 104,
    restaurantId: 1,
    name: "Shahi Paneer Cream Masala",
    description: "Fresh cottage cheese diamonds blanketed in dense cashew, cream, and cardamom aromatic gravy.",
    price: 390.0,
    category: "Mains",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.4,
    reviewCount: 6,
    imageUrl: "/images/dishes/104.png"
  },
  {
    id: 105,
    restaurantId: 1,
    name: "Imperial Dal Bukhara",
    description: "Slow-cooked creamy black lentils with hand-churned butter, simmered overnight for that signature velvety texture.",
    price: 320.0,
    category: "Mains",
    isVeg: true,
    isPopular: true,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.8,
    reviewCount: 19,
    imageUrl: "/images/dishes/105.png"
  },
  {
    id: 106,
    restaurantId: 1,
    name: "Nawabi Murgh Dum Biryani",
    description: "Fragrant long-grain Dehraduni basmati rice layered with juicy spiced chicken, fresh mint, and pure kashmiri saffron.",
    price: 480.0,
    category: "Biryani",
    isVeg: false,
    isPopular: true,
    spiceLevel: 3,
    isSpecial: true,
    rating: 4.8,
    reviewCount: 15,
    imageUrl: "/images/dishes/106.png"
  },
  {
    id: 107,
    restaurantId: 1,
    name: "Sizzling Garlic Butter Naan",
    description: "Tandoor baked hand-stretched leavened flatbread glazed lavishly with minced garlic butter.",
    price: 80.0,
    category: "Breads",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.6,
    reviewCount: 22,
    imageUrl: "/images/dishes/107.png"
  },
  {
    id: 108,
    restaurantId: 1,
    name: "Crispy Laccha Paratha",
    description: "Flaky, crispy, multi-layered golden whole wheat flour flatbread cooked over clay griddles.",
    price: 70.0,
    category: "Breads",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.5,
    reviewCount: 8,
    imageUrl: "/images/dishes/108.png"
  },
  {
    id: 109,
    restaurantId: 1,
    name: "Rose Cardamom Gulab Jamun",
    description: "Sponge-soft golden khoya dumplings soaked in warm cardamom and organic rose-water simple syrup.",
    price: 150.0,
    category: "Desserts",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.7,
    reviewCount: 10,
    imageUrl: "/images/dishes/109.png"
  },
  {
    id: 110,
    restaurantId: 1,
    name: "Kesar Pista Shahi Kulfi",
    description: "Traditional Indian slow-churned frozen cream dessert packed with rich saffron thread, crushed pistachios, and almonds.",
    price: 180.0,
    category: "Desserts",
    isVeg: true,
    isPopular: true,
    spiceLevel: 1,
    isSpecial: true,
    rating: 4.9,
    reviewCount: 14,
    imageUrl: "/images/dishes/110.png"
  },

  // Dakshin Palace (restaurantId = 2)
  {
    id: 201,
    restaurantId: 2,
    name: "Ghee Roast Masala Dosa",
    description: "Stunningly crispy paper-thin fermented rice crepe brushed with pure spiced ghee, filled with golden mustard potato mash.",
    price: 180.0,
    category: "Starters",
    isVeg: true,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: true,
    rating: 4.9,
    reviewCount: 21,
    imageUrl: "/images/dishes/201.png"
  },
  {
    id: 202,
    restaurantId: 2,
    name: "Chettinad Pepper Chicken Fry",
    description: "Fiery dry-fried tender chicken chunks tossed with fresh hand-ground black pepper, roasted curry leaves, and local fennel.",
    price: 360.0,
    category: "Starters",
    isVeg: false,
    isPopular: true,
    spiceLevel: 3,
    isSpecial: true,
    rating: 4.8,
    reviewCount: 14,
    imageUrl: "/images/dishes/202.png"
  },
  {
    id: 203,
    restaurantId: 2,
    name: "Classic Steamed Sambar Vadai",
    description: "Savory fried crisp lentil donuts fully immersed in piping hot spicy sambar stew, garnished with mustard seeds.",
    price: 120.0,
    category: "Starters",
    isVeg: true,
    isPopular: false,
    spiceLevel: 2,
    isSpecial: false,
    rating: 4.4,
    reviewCount: 5,
    imageUrl: "/images/dishes/203.png"
  },
  {
    id: 204,
    restaurantId: 2,
    name: "Coastal Malabar Prawn Curry",
    description: "Juicy shrimp slow-cooked in a traditional spiced coconut milk reduction with green chili and raw mango.",
    price: 520.0,
    category: "Mains",
    isVeg: false,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: true,
    rating: 4.9,
    reviewCount: 18,
    imageUrl: "/images/dishes/204.png"
  },
  {
    id: 205,
    restaurantId: 2,
    name: "Paneer Karaikudi Spice",
    description: "Cottage cheese pieces simmered in a bold and fiery tomato-onion Chettinad spice masala.",
    price: 380.0,
    category: "Mains",
    isVeg: true,
    isPopular: false,
    spiceLevel: 3,
    isSpecial: false,
    rating: 4.5,
    reviewCount: 7,
    imageUrl: "/images/dishes/205.png"
  },
  {
    id: 206,
    restaurantId: 2,
    name: "Malabar Jackfruit Dum Biryani",
    description: "Tender raw jackfruit chunks marinated in southern herbs and slow-steamed with Kaima rice.",
    price: 395.0,
    category: "Biryani",
    isVeg: true,
    isPopular: false,
    spiceLevel: 2,
    isSpecial: false,
    rating: 4.6,
    reviewCount: 6,
    imageUrl: "/images/dishes/206.png"
  },
  {
    id: 207,
    restaurantId: 2,
    name: "Lacy Malabar Parotta",
    description: "Multi-layered, flaky, hand-waved soft southern golden parotta, ideal to mop up curries.",
    price: 60.0,
    category: "Breads",
    isVeg: true,
    isPopular: true,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.7,
    reviewCount: 16,
    imageUrl: "/images/dishes/207.png"
  },
  {
    id: 208,
    restaurantId: 2,
    name: "Appam with Sweet Coconut Milk",
    description: "Soft, puffy bowl-shaped rice pancakes with thin crispy edges served with sweetened cardamon coconut milk.",
    price: 110.0,
    category: "Breads",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.3,
    reviewCount: 4,
    imageUrl: "/images/dishes/208.png"
  },
  {
    id: 209,
    restaurantId: 2,
    name: "Chilled Elaneer Payasam",
    description: "A rich, chilled dessert made from tender coconut water pulp and condensed milk infused with green cardamom.",
    price: 165.0,
    category: "Desserts",
    isVeg: true,
    isPopular: true,
    spiceLevel: 1,
    isSpecial: true,
    rating: 4.8,
    reviewCount: 12,
    imageUrl: "/images/dishes/209.png"
  },

  // Clay Oven Punjabi (restaurantId = 3)
  {
    id: 301,
    restaurantId: 3,
    name: "Amritsari Machhi Fry",
    description: "Crispy carom seed-infused gram flour batter-coated fried river fish fillets served with spicy mint chutney.",
    price: 390.0,
    category: "Starters",
    isVeg: false,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: false,
    rating: 4.7,
    reviewCount: 10,
    imageUrl: "/images/dishes/301.png"
  },
  {
    id: 302,
    restaurantId: 3,
    name: "Hara Bhara Kebab",
    description: "Pan-fried patties made of pureed spinach, garden peas, potato, and stuffed with chopped cashews.",
    price: 240.0,
    category: "Starters",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.4,
    reviewCount: 3,
    imageUrl: "/images/dishes/302.png"
  },
  {
    id: 303,
    restaurantId: 3,
    name: "Dhaba style Kadhai Paneer",
    description: "Fresh paneer rectangles and crisp bell peppers tossed with spicy whole dry chilies and crushed coriander seeds.",
    price: 360.0,
    category: "Mains",
    isVeg: true,
    isPopular: true,
    spiceLevel: 3,
    isSpecial: true,
    rating: 4.8,
    reviewCount: 13,
    imageUrl: "/images/dishes/303.png"
  },
  {
    id: 304,
    restaurantId: 3,
    name: "Sarson Ka Saag & Makki Roti",
    description: "Fresh winter mustard greens churned with white butter, accompanied by flatbread made of yellow cornmeal.",
    price: 310.0,
    category: "Mains",
    isVeg: true,
    isPopular: false,
    spiceLevel: 2,
    isSpecial: true,
    rating: 4.7,
    reviewCount: 9,
    imageUrl: "/images/dishes/304.png"
  },
  {
    id: 305,
    restaurantId: 3,
    name: "Amritsari Spicy Butter Chicken",
    description: "Flame-charred clay oven grilled chicken tossed with spicy tomato cream gravy and dry fenugreek.",
    price: 420.0,
    category: "Mains",
    isVeg: false,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: false,
    rating: 4.8,
    reviewCount: 11,
    imageUrl: "/images/dishes/305.png"
  },
  {
    id: 306,
    restaurantId: 3,
    name: "Pind Da Mutton Dum Biryani",
    description: "Fragrant basmati layered with tender slow-braised mutton shanks in robust Punjabi garam masala spices.",
    price: 540.0,
    category: "Biryani",
    isVeg: false,
    isPopular: false,
    spiceLevel: 3,
    isSpecial: true,
    rating: 4.7,
    reviewCount: 8,
    imageUrl: "/images/dishes/306.png"
  },
  {
    id: 307,
    restaurantId: 3,
    name: "Stuffed Amritsari Potato Kulcha",
    description: "Crusted leavened flatbread stuffed with tangy spicy potato-onion mash, baked in tandoor and brushed with ghee.",
    price: 120.0,
    category: "Breads",
    isVeg: true,
    isPopular: true,
    spiceLevel: 2,
    isSpecial: false,
    rating: 4.8,
    reviewCount: 14,
    imageUrl: "/images/dishes/307.png"
  },
  {
    id: 308,
    restaurantId: 3,
    name: "Butter Tandoori Roti",
    description: "Standard clay oven-cooked fresh whole wheat bread with a light brush of salted butter.",
    price: 40.0,
    category: "Breads",
    isVeg: true,
    isPopular: false,
    spiceLevel: 1,
    isSpecial: false,
    rating: 4.2,
    reviewCount: 5,
    imageUrl: "/images/dishes/308.png"
  },
  {
    id: 309,
    restaurantId: 3,
    name: "Desi Ghee Moong Dal Halwa",
    description: "Warm, decadent split-lentil pudding cooked with heavy butter oil, saffron threads, and crushed nuts.",
    price: 140.0,
    category: "Desserts",
    isVeg: true,
    isPopular: true,
    spiceLevel: 1,
    isSpecial: true,
    rating: 4.9,
    reviewCount: 16,
    imageUrl: "/images/dishes/309.png"
  }
];

export const loyaltyRewards: LoyaltyReward[] = [
  {
    id: "r1",
    title: "Saffron Feast Discount",
    pointsCost: 100,
    discountAmount: 50.0,
    description: "Get ₹50 flat off on any order. Savor extra crispy naans!"
  },
  {
    id: "r2",
    title: "Royal Biryani Coupon",
    pointsCost: 250,
    discountAmount: 150.0,
    description: "Get ₹150 flat off. Perfect for aromatic dum biryanis!"
  },
  {
    id: "r3",
    title: "Tandoor Connoisseur Gift",
    pointsCost: 500,
    discountAmount: 320.0,
    description: "Get ₹320 flat off. Good for a free starter or dessert package!"
  },
  {
    id: "r4",
    title: "Imperial Maharaja Voucher",
    pointsCost: 800,
    discountAmount: 550.0,
    description: "Get ₹550 off. Perfect for a grand dinner feast!"
  }
];

export const initialReviews: Review[] = [
  {
    id: 1,
    restaurantId: 1,
    userName: "Rahul Sharma",
    rating: 5,
    comment: "Unbelievably rich Butter Chicken! The saffron paneer was also extremely soft.",
    timestamp: Date.now() - 2 * 3600000
  },
  {
    id: 2,
    restaurantId: 1,
    userName: "Preeti Iyer",
    rating: 5,
    comment: "Exquisite ambiance and the Royal Dal Bukhara tastes exactly like the original. Saffron Taj is Delhi's best Mughlai spot.",
    timestamp: Date.now() - 12 * 3600000
  },
  {
    id: 3,
    restaurantId: 1,
    menuItemId: 103,
    menuItemName: "Grand Royal Butter Chicken",
    userName: "Aman Verma",
    rating: 5,
    comment: "The absolute benchmark for butter chicken. Smoky, perfectly sweet, rich honey undertones.",
    timestamp: Date.now() - 500000
  },
  {
    id: 4,
    restaurantId: 1,
    menuItemId: 105,
    menuItemName: "Imperial Dal Bukhara",
    userName: "Devendra K.",
    rating: 4,
    comment: "Signature soft cooked cream lentils. Meticulously spiced and buttery.",
    timestamp: Date.now() - 1700000
  },
  {
    id: 5,
    restaurantId: 2,
    userName: "Ananth Krishnan",
    rating: 5,
    comment: "Breathtaking filter coffee and crisp ghee roast dosa. Genuine taste of Tamil Nadu and Bengaluru hospitality.",
    timestamp: Date.now() - 5 * 3600000
  },
  {
    id: 6,
    restaurantId: 2,
    menuItemId: 201,
    menuItemName: "Ghee Roast Masala Dosa",
    userName: "Anuradha S.",
    rating: 5,
    comment: "Extremely crisp, thick golden coat, and the potato filling is beautifully yellow-spiced.",
    timestamp: Date.now() - 1800000
  },
  {
    id: 7,
    restaurantId: 3,
    userName: "Jaspreet Singh",
    rating: 5,
    comment: "As authentic as Amritsar's by-lanes! Best Sarson ka Saag and Crispy Machhi in town.",
    timestamp: Date.now() - 25 * 3600000
  },
  {
    id: 8,
    restaurantId: 1,
    menuItemId: 106,
    menuItemName: "Nawabi Murgh Dum Biryani",
    userName: "Kabir Mehta",
    rating: 5,
    comment: "The chicken was exceptionally tender, and the fragrant saffron notes in the Dehraduni basmati rice were sublime.",
    timestamp: Date.now() - 4 * 3600000
  },
  {
    id: 9,
    restaurantId: 1,
    menuItemId: 110,
    menuItemName: "Kesar Pista Shahi Kulfi",
    userName: "Riya Sen",
    rating: 5,
    comment: "Rich, dense, and authentic kulfi. The crunch of pistachios and saffron threads makes it a perfect ending.",
    timestamp: Date.now() - 6 * 3600000
  },
  {
    id: 10,
    restaurantId: 2,
    menuItemId: 202,
    menuItemName: "Chettinad Pepper Chicken Fry",
    userName: "Karthik Raja",
    rating: 5,
    comment: "The pepper punch is absolutely authentic. Fresh curry leaves and fennel roasted to perfection.",
    timestamp: Date.now() - 8 * 3600000
  },
  {
    id: 11,
    restaurantId: 2,
    menuItemId: 204,
    menuItemName: "Coastal Malabar Prawn Curry",
    userName: "Meera Nair",
    rating: 5,
    comment: "Fabulous blend of coconut milk and sour kokum. Reminded me of my grandmother's coastal recipe!",
    timestamp: Date.now() - 10 * 3600000
  },
  {
    id: 12,
    restaurantId: 3,
    menuItemId: 303,
    menuItemName: "Dhaba style Kadhai Paneer",
    userName: "Gurpreet Singh",
    rating: 4,
    comment: "Spicy wok-cooked goodness. The crushed coriander seeds gave it that perfect rustic dhaba texture.",
    timestamp: Date.now() - 14 * 3600000
  },
  {
    id: 13,
    restaurantId: 3,
    menuItemId: 309,
    menuItemName: "Desi Ghee Moong Dal Halwa",
    userName: "Vikram Kapoor",
    rating: 5,
    comment: "Extremely rich and comforting. You can tell they use genuine desi ghee and slow roast it for hours.",
    timestamp: Date.now() - 16 * 3600000
  },
  {
    id: 14,
    restaurantId: 1,
    userName: "Neha Gupta",
    rating: 4,
    comment: "Beautiful Mughlai heritage flavors. Service was exceptionally prompt and packaging was solid.",
    timestamp: Date.now() - 20 * 3600000
  },
  {
    id: 15,
    restaurantId: 2,
    userName: "Sanjay Rao",
    rating: 5,
    comment: "Best South Indian spread in town. The filter coffee and coastal prawn curry are absolute standouts.",
    timestamp: Date.now() - 22 * 3600000
  },
  {
    id: 16,
    restaurantId: 3,
    userName: "Simran Kaur",
    rating: 4,
    comment: "Flavors are bold and robust. The Amritsari kulchas were warm, buttery, and packed with spices.",
    timestamp: Date.now() - 28 * 3600000
  },
  {
    id: 17,
    restaurantId: 1,
    menuItemId: 101,
    menuItemName: "Tandoori Saffron Paneer Tikka",
    userName: "Rajesh Khanna",
    rating: 5,
    comment: "Mouth-watering paneer cubes! Saffron aroma was subtle but present, and the char was perfect.",
    timestamp: Date.now() - 32 * 3600000
  },
  {
    id: 18,
    restaurantId: 1,
    menuItemId: 107,
    menuItemName: "Sizzling Garlic Butter Naan",
    userName: "Aditi Roy",
    rating: 5,
    comment: "Garlic flavor was rich and buttery without being overwhelming. Best naan to pair with Dal Bukhara!",
    timestamp: Date.now() - 36 * 3600000
  },
  {
    id: 19,
    restaurantId: 2,
    menuItemId: 207,
    menuItemName: "Lacy Malabar Parotta",
    userName: "Pranav Pillai",
    rating: 5,
    comment: "Flaky, layered, and incredibly soft. Perfect consistency to absorb the Malabar prawn curry.",
    timestamp: Date.now() - 40 * 3600000
  },
  {
    id: 20,
    restaurantId: 2,
    menuItemId: 209,
    menuItemName: "Chilled Elaneer Payasam",
    userName: "Divya Teja",
    rating: 5,
    comment: "Light, refreshing, and just the right level of sweetness. The tender coconut pieces add a great bite.",
    timestamp: Date.now() - 44 * 3600000
  },
  {
    id: 21,
    restaurantId: 3,
    menuItemId: 305,
    menuItemName: "Amritsari Spicy Butter Chicken",
    userName: "Harbhajan S.",
    rating: 5,
    comment: "Unlike regular sweet butter chicken, this has a wonderful spicy heat and a deep smoky clay oven taste.",
    timestamp: Date.now() - 48 * 3600000
  },
  {
    id: 22,
    restaurantId: 3,
    menuItemId: 307,
    menuItemName: "Stuffed Amritsari Potato Kulcha",
    userName: "Paramjit Singh",
    rating: 5,
    comment: "Crispy outer layer with a soft, flavorful potato mash stuffing. Felt like eating at a street stall in Amritsar.",
    timestamp: Date.now() - 52 * 3600000
  },
  {
    id: 23,
    restaurantId: 1,
    menuItemId: 109,
    menuItemName: "Rose Cardamom Gulab Jamun",
    userName: "Sonia Verma",
    rating: 4,
    comment: "Extremely soft and warm, though slightly sweeter than I usually prefer. Beautiful rose fragrance.",
    timestamp: Date.now() - 56 * 3600000
  },
  {
    id: 24,
    restaurantId: 2,
    menuItemId: 205,
    menuItemName: "Paneer Karaikudi Spice",
    userName: "Venkatesh Prasad",
    rating: 4,
    comment: "Perfect heat level and rich Chettinad flavor profile. The paneer was incredibly fresh.",
    timestamp: Date.now() - 60 * 3600000
  },
  {
    id: 25,
    restaurantId: 3,
    menuItemId: 304,
    menuItemName: "Sarson Ka Saag & Makki Roti",
    userName: "Manpreet Kaur",
    rating: 5,
    comment: "Authentic winter greens flavor, served with delicious fresh makki roti. Reminds me of home!",
    timestamp: Date.now() - 64 * 3600000
  },
  {
    id: 26,
    restaurantId: 1,
    menuItemId: 104,
    menuItemName: "Shahi Paneer Cream Masala",
    userName: "Arjun Dev",
    rating: 4,
    comment: "Rich, creamy, and velvety gravy. Very mild spices, perfect for children or anyone who prefers non-spicy.",
    timestamp: Date.now() - 68 * 3600000
  },
  {
    id: 27,
    restaurantId: 3,
    menuItemId: 301,
    menuItemName: "Amritsari Machhi Fry",
    userName: "Nikhil Salian",
    rating: 5,
    comment: "Perfect carom seeds flavor in the batter. Super crispy outside, flaky and moist fish inside.",
    timestamp: Date.now() - 72 * 3600000
  }
];

export const initialLoyalty: UserLoyalty = {
  id: 1,
  pointsBalance: 380,
  pointsEarnedTotal: 380,
  tier: "Silver"
};
